server.port=8082
spring.application.name=user-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sritel}
spring.datasource.username=${DB_USER:sritel}
spring.datasource.password=${DB_PASS:sritel}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
